version: '3.3'

services:
    redis:
        restart: unless-stopped
        image: redislabs/redisearch
        ports:
            - '6379:6379'

    kisscam:
        image: dcr.fredkiss.dev/kisscam-api
        restart: unless-stopped
        ports:
            - '8082:80'
        environment:
            - REDIS_URL=redis://redis:6379
