# This is a basic workflow to help you get started with Actions

name: Continous Integration For Backend

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - "back/**"
      - .github/workflows/back.yaml
      - ./package.json
      - ./pnpm-lock.yaml
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab+1
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 7.1.0
      - name: Use Node.js version 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install --prefix shared
      - run: pnpm run build --prefix shared
      - run: pnpm install --prefix back
      - run: pnpm test --prefix back
